### ISSUE TITLE
FeatureMatchingLoss

### ISSUE THREAD

**Issue by abylouw** [wetdog/wavenext_pytorch#2]
Hi,

I am trying to train a model using a config similar to the wavenext.yaml one.
The data is a subset of LibriTTS that I have downsampled to 22050.

I am not exactly sure what the num_samples in the train_params and val_params are, can you please explain?

Also, I am getting a tensor size mismatch at:

loss += torch.mean(torch.abs(rl - gl))

in the FeatureMatchingLoss function. 

The two tensors always differ by 1 size, no matter what data I give it.
Can you please assist?

**Comment by wetdog** [comment]
Hi Aby, 

num_samples are used in the dataset loader to get a random segment of the audio, for training are equivalent to grabbing 0.74 seconds and ~ 2.2 seconds at validation time. There's actually a resampling step if the sample rate don't match the one defined in the conf. 


```python
    def __getitem__(self, index: int) -> torch.Tensor:
        audio_path = self.filelist[index]
        y, sr = torchaudio.load(audio_path)
        if y.size(0) > 1:
            # mix to mono
            y = y.mean(dim=0, keepdim=True)
        gain = np.random.uniform(-1, -6) if self.train else -3
        y, _ = torchaudio.sox_effects.apply_effects_tensor(y, sr, [["norm", f"{gain:.2f}"]])
        if sr != self.sampling_rate:
            y = torchaudio.functional.resample(y, orig_freq=sr, new_freq=self.sampling_rate)
        if y.size(-1) < self.num_samples:
            pad_length = self.num_samples - y.size(-1)
            padding_tensor = y.repeat(1, 1 + pad_length // y.size(-1))
            y = torch.cat((y, padding_tensor[:, :pad_length]), dim=1)
        elif self.train:
            start = np.random.randint(low=0, high=y.size(-1) - self.num_samples + 1)
            y = y[:, start : start + self.num_samples]
        else:
            # During validation, take always the first segment for determinism
            y = y[:, : self.num_samples]
```

I would check the error that you mention but probably could be the padding configuration which affects the center argument in the mel spectrogram.

**Comment by abylouw** [comment]
```
model:                                                                                                    
  class_path: vocos.experiment.VocosExp                                                                   
  init_args:                                                                                              
    sample_rate: 22050                                                                                    
    initial_learning_rate: 1e-4                                                                           
    mel_loss_coeff: 45                                                                                    
    mrd_loss_coeff: 0.1 # original value 0.1                                                              
    num_warmup_steps: 500 # Optimizers warmup steps
    pretrain_mel_steps: 0  # 0 means GAN objective from the first iteration

    # automatic evaluation
    evaluate_utmos: true
    evaluate_pesq: true
    evaluate_periodicty: true

    feature_extractor:
      class_path: vocos.feature_extractors.MelSpectrogramFeatures
      init_args:
        sample_rate: 22050
        n_fft: 1024
        hop_length: 256
        n_mels: 80
        padding: center
        f_min: 0
        f_max: 8000
        norm: "slaney"
        mel_scale: "slaney"
        clip_val: 1e-5
```

I changed the padding from "same" to "center" and now get the following error:

[rank0]:   File "/home/app/wavenext_pytorch/metrics/periodicity.py", line 89, in calculate_periodicity_metrics
[rank0]:     periodicity_loss = np.sqrt(((pred_periodicity - true_periodicity) ** 2).mean(axis=1)).mean()
[rank0]: ValueError: operands could not be broadcast together with shapes (16,95) (16,94)

**Comment by wetdog** [comment]
can you check with this conf, I used this to train the checkpoints

```
seed_everything: 4444

data:
  class_path: vocos.dataset.VocosDataModule
  init_args:
    train_params:
      filelist_path: ???
      sampling_rate: 22050
      num_samples: 16384
      batch_size: 16
      num_workers: 8

    val_params:
      filelist_path: ???
      sampling_rate: 22050
      num_samples: 48384
      batch_size: 16
      num_workers: 8

model:
  class_path: vocos.experiment.VocosExp
  init_args:
    sample_rate: 22050
    initial_learning_rate: 4e-4
    mel_loss_coeff: 45
    mrd_loss_coeff: 1.0 # original value 0.1
    num_warmup_steps: 500 # Optimizers warmup steps
    pretrain_mel_steps: 0  # 0 means GAN objective from the first iteration

    # automatic evaluation
    evaluate_utmos: true
    evaluate_pesq: true
    evaluate_periodicty: true

    feature_extractor:
      class_path: vocos.feature_extractors.MelSpectrogramFeatures
      init_args:
        sample_rate: 22050
        n_fft: 1024
        hop_length: 256
        n_mels: 80
        padding: same
        f_min: 0
        f_max: 8000
        norm: "slaney"
        mel_scale: "slaney"
        clip_val: 1e-5


    backbone:
      class_path: vocos.models.VocosBackbone
      init_args:
        input_channels: 80
        dim: 512
        intermediate_dim: 1536
        num_layers: 8

    head:
      class_path: vocos.heads.WaveNextHead
      init_args:
        dim: 512
        n_fft: 1024
        hop_length: 256
        padding: same
    
    melspec_loss:
      class_path: vocos.loss.MelSpecReconstructionLoss
      init_args:
        sample_rate: 22050
        n_fft: 1024
        hop_length: 256
        n_mels: 128
        f_min: 0
        f_max: 11025
        norm: "slaney"
        mel_scale: "slaney"
        clip_val: 1e-5

```
